[project]
name = "dlagent2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "claude-agent-sdk>=0.1.20",
    "lark-oapi>=1.5.2",
    "python-dotenv>=1.0.0",
]
